name: amplify
config:
  webroot: public
events:
  post-db-import:
    - database: /app/test-script.sh
services:
  appserver:
    type: ruby:2.5.3
    port: 3000
    command: bundle exec rails s
    build:
      - gem install bundler
      - bundle install
  database:
    type: postgres
tooling:
  psql-verify:
    service: database
    user: root
    cmd: psql -U postgres database -C "\dt"
  'db-import <file>':
    service: :host
    description: Imports a pgsql dump into the database service
    cmd: /helpers/sql-import.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Preserve existing database before import
        boolean: true
        default: false
        alias:
          - n
