name: amplify
config:
  webroot: public
events:
  post-db-import:
    - database: /app/helpers/test-script.sh
services:
  appserver:
    type: compose
    services:
      image: bitnami/rails
      command: "bundle exec rails s -b 0.0.0.0 -p 3000"
      user: root
      environment:
        GEM_HOME: /app/vendor
        BUNDLE_DEFAULT_INSTALL_USERS_PATH: /app/vendor
        DATABASE_HOST: database
        DATABASE_NAME: rails
    build:
      - gem install bundler
      - bundle install
      - npm install
      - /app/helpers/lando-db-config.sh
      - /app/helpers/lando-app-config.sh
  redis:
    type: redis:6
    portforward: true
  database:
    type: postgres
    creds:
      user: rails
      password: rails
      database: rails
  sidekiq:
    type: compose
    services:
      image: bitnami/rails
      command: bundle exec sidekiq
    build:
      - gem install bundler
      - bundle install
proxy:
  appserver:
    - amplify.lndo.site:3000
tooling:
  rails:
    service: appserver
  bundle:
    service: appserver
  rake:
    service: appserver
  npm:
    service: appserver
  npx:
    service: appserver
  psql-verify:
    service: database
    user: root
    cmd: psql -U postgres database -C "\dt"
  'db-import <file>':
    service: :host
    description: Imports a pgsql dump into the database service
    cmd: /helpers/sql-import.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Preserve existing database before import
        boolean: true
        default: false
        alias:
          - n
