development:
  host: <%= ENV['DB_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  port: 5432
  pool: 5
  timeout: 5000
