# Use the official Ruby image with version 3.0.0 as the base image
FROM ruby:3.0.0

# Set the working directory in the container
WORKDIR /app

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install essential dependencies
RUN apt-get update \
    && apt-get install -y \
        nodejs \
        npm \
        chromium \
        chromium-driver \
        postgresql-client \
        bash \
    && rm -rf /var/lib/apt/lists/*

# Add user.
RUN addgroup --gid 1000 amplify
RUN adduser --gecos "" \
    --disabled-password \
    --ingroup amplify \
    --shell /bin/false --uid 1000 amplify
RUN export HOME=/app

# Set Chrome binary path
ENV CHROME_BIN=/usr/bin/chromium

# Copy the Gemfile and Gemfile.lock into the image and install gems
COPY Gemfile Gemfile.lock ./

# Install dependencies.
RUN bundle install
RUN npm install

# Set bundle cache permissions so CLI user can update packages.
# Don't do this in a production Dockerfile!
RUN chmod -R a+rw /usr/local/bundle
# Purge the cache directory.
RUN rm -r /usr/local/bundle/cache/*

# Set up user.
USER amplify

# Copy the rest of the application code into the image
COPY . .

# CMD
ENTRYPOINT ["/bin/bash", "-c", "sleep infinity"]
